FROM golang:1.20 AS builder


RUN apt-get update && apt-get install -y gcc git musl-dev musl-tools

WORKDIR /workspace
COPY . .

RUN go mod download
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 CC=musl-gcc CGO_LDFLAGS="-static" go build -a -o devbox cmd/devbox/main.go

