name: Publish to Dockerhub ( frontend )

on:
    workflow_dispatch:
      inputs:
        tags:
          description: 'Release Tags'

jobs:
    update_dockerhub:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASS }}

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                node-version: '16.18'
            - name: Cache
              uses: actions/cache@v1
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/packagge-lock.json')}}
                restore-keys: |
                    ${{ runner.os }}-node-
            - name: Bootstrap
              run: |
                npm install
            - run: npm i -g @quasar/cli
            - run: npm install
            - name: Build
              run: npm run app:build                  
            - name: Build and push Docker image 
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: beclab/devbox:${{ github.event.inputs.tags }}
                  file: Dockerfile