name: Publish to Dockerhub ( server )

on:
    workflow_dispatch:
      inputs:
        tags:
          description: 'Release Tags'

jobs:
    update_dockerhub:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASS }}

            - name: Download release check-chart
              uses: dsaltares/fetch-gh-release-asset@master
              with:
                file: check-chart_0.0.1_linux_amd64.tar.gz
                repo: beclab/check-chart
                target: check-chart.tar.gz
                version: tags/v0.0.1
                token: ${{ secrets.DOWNLOAD_TOKEN }} 

            - name: unpack check-chart
              run: |
                tar zxvf check-chart.tar.gz

            - name: Build and push Docker image 
              uses: docker/build-push-action@v3
              with:
                  push: true
                  context: .
                  tags: beclab/devbox-server:${{ github.event.inputs.tags }}
                  file: Dockerfile.server